spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5434/demo?currentSchema=bookings
    username: postgres
    password: mysecretpassword
    driverClassName: org.postgresql.Driver

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml